# Generated by Django 2.2.5 on 2020-04-13 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_posts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='jobs',
        ),
    ]
