# Generated by Django 2.2.5 on 2020-04-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_delete_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
