# Generated by Django 2.2.5 on 2020-04-18 14:38

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_remove_posts_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='content',
            field=tinymce.models.HTMLField(default='content', verbose_name='content'),
            preserve_default=False,
        ),
    ]
