# Generated by Django 2.2.5 on 2020-04-18 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_posts_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='content',
            new_name='contents',
        ),
    ]
