# Generated by Django 2.2.5 on 2020-04-21 12:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20200418_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='contents',
        ),
        migrations.AddField(
            model_name='posts',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
