# Generated by Django 2.2.5 on 2020-04-22 04:20

from django.db import migrations
from ckeditor.fields import RichTextField


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20200421_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=RichTextField(default=True),
        ),
    ]
