# Generated by Django 2.2.5 on 2020-04-24 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_auto_20200422_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='next_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='jobs.posts'),
        ),
        migrations.AddField(
            model_name='posts',
            name='previous_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous', to='jobs.posts'),
        ),
    ]
