# Generated by Django 2.2.5 on 2020-06-05 06:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_auto_20200426_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='avatar'),
        ),
    ]
