# Generated by Django 3.0.8 on 2020-07-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_posts_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='Desc',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
