# Generated by Django 3.0.8 on 2020-08-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0023_author_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
