# Generated by Django 2.2.5 on 2020-04-14 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signups',
            new_name='ignups',
        ),
    ]
