# Generated by Django 2.2.5 on 2020-01-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=260)),
                ('Publ_date', models.DateTimeField()),
                ('Body', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
