# Generated by Django 2.2.5 on 2020-04-06 06:02

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
